InternetShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('shop.urls', 'home'), namespace='home')),
    # path('home/', include('shop.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.index, name="mainpage"),
    path('index/', views.redirect_to_mainpage, name="mainpage_index"),
    path('home/', views.redirect_to_mainpage, name="mainpage_red"),
    path('<int:item_id>/', views.detail, name='detail'),
    path('search/', views.search, name="search"),
    path('<str:cat>/', views.category_filter, name="category_filter"),
]

shop/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models


class Category(models.Model):
    category_name = models.CharField('название категории', max_length=50)

    def __str__(self):
        return 'Категория: ' + self.category_name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Subcategory(models.Model):
    subcategory_name = models.CharField('название подкатегории', max_length=50)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.subcategory_name

    class Meta:
        verbose_name = 'Подкатегория'
        verbose_name_plural = 'Подкатегории'


class Item(models.Model):
    category = models.ForeignKey(Subcategory, on_delete=models.CASCADE)
    name = models.CharField('название товара', max_length=50)
    image = models.ImageField()
    price = models.FloatField()

    rating = models.FloatField('rating', validators=[
        MaxValueValidator(5),
        MinValueValidator(0)
    ], blank=True)

    MEN = 'men'
    WOMEN = 'women'

    sex_list = [
        (MEN, 'Men'),
        (WOMEN, 'Women'),
    ]
    sex = models.CharField(
        max_length=30,
        choices=sex_list,
        default=MEN,
    )

    XXS = 'XXS'
    XS = 'XS'
    S = 'S'
    M = 'M'
    L = 'L'
    XL = 'XL'
    XXL = 'XXL'

    size_list = [
        (XXS, 'XXS'),
        (XS, 'XS'),
        (S, 'S'),
        (M, 'M'),
        (L, 'L'),
        (XL, 'XL'),
        (XXL, 'XXL'),
    ]
    size = models.CharField(
        max_length=30,
        choices=size_list,
        default=S,
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class Comment(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    author_name = models.CharField('имя автора', max_length=50)
    comment_text = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

shop/views.py
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render
from django.urls import reverse

from .models import Item, Subcategory


def index(request):
    items_list = Item.objects.all()
    categories_list = Subcategory.objects.all()
    return render(request, 'index.html', {'items_list': items_list, 'categories_list': categories_list})


def redirect_to_mainpage(request):
    return HttpResponseRedirect(reverse('shop:mainpage'))


def detail(request, item_id):
    try:
        item = Item.objects.get(id=item_id)
    except:
        raise Http404('Товар не найден')
    categories_list = Subcategory.objects.all()

    return render(request, 'detail.html', {'item': item, 'categories_list': categories_list})


def search(request):
    items_list = Item.objects.filter(name__icontains=request.GET['searchword'].capitalize())
    categories_list = Subcategory.objects.all()
    return render(request, 'index.html', {'items_list': items_list, 'categories_list': categories_list})


def category_filter(request, cat):
    items_list = Item.objects.filter(category__subcategory_name=cat)
    categories_list = Subcategory.objects.all()
    return render(request, 'index.html', {'items_list': items_list, 'categories_list': categories_list})

shop/templates/detail.html
{% extends "base.html" %}

{% block title %}
    {{item.name}}
{% endblock title %}

{% block content %}
	<ul class="categories-list">
        {% if categories_list %}
            {% for i in categories_list %}
                <li><a href="{% url 'shop:category_filter' i %}">{{i}}</a></li>
            {% endfor %}
        {% endif %}
    </ul>
    <div class="block-item-detail">
    	<h1>{{item.name}}</h1>
		<img src="{{ MEDIA_URL }}{{ item.image.url }}" style="height: 600px; width: 400px; display: inline-block;">
		<h4 style="display: inline-block; ">{{item.price}}</h4>
    </div>
{% endblock content %}

shop/templates/index.html
{% extends "base.html" %}

{% block content %}
    <div class="content-root">
        <ul class="categories-list">
            {% if categories_list %}
                {% for i in categories_list %}
                    <li><a href="{% url 'shop:category_filter' i %}">{{i}}</a></li>
                {% endfor %}
            {% endif %}
        </ul>

        
        {% if items_list %}
                <div class="all-items">
                	{% for i in items_list %}
                		<div class="block-item">
    	            		<img src="{{ MEDIA_URL }}{{ i.image.url }}">
    	            		<h6><a href="{% url 'home:detail' i.id %}" class="label label-primary">{{i.name}}</a></h6>
                		</div>
                	{% endfor %}
                </div>

        {% else %}
            <h5 style="padding-left: 270px">No items found</h5>
        {% endif %}
    </div>
{% endblock content %}